### ISSUE TITLE
[Feature] HID input

### ISSUE THREAD

**Issue by nieknooijens** [guusw/unnamed-sdvx-clone#14]
Hi

Now the game is fully operational on linux I'm going to build a SDVX controller using parts from arcadewinkel.nl (they have nice buttons and switches for the real arcade experience) I will program the controller to act like a normal Xbox gamepad similar to dance pads and other peripherals. 
(you can also buy them here: http://www.gamo2.com/en/index.php?dispatch=products.view&product_id=314)
Therefore we need some way to map the controller to the program using a nice GUI controller mapping utility.

**Comment by Drewol** [comment]
The Gamo2 sdvx controllers act as keyboard and mouse (mouse X & Y for knobs) but the other popular controller, virgoo turbocharger, acts as a HID gamepad

**Comment by guusw** [comment]
I'll add a configuration menu for gamepads / mouse bindings eventually. Earlier on you can probably configure those manually from the config file (so that it at least works without having the menu yet).

**Comment by nieknooijens** [comment]
I'm also willing to help programming, you don't have to do everything yourself!

**Comment by guusw** [comment]
Yeah sure, feel free to add other features here if you think they're not already in the project description.
If you wan't to see if you can help  with this specific thing you can check out Main/Input.hpp,.cpp.
I do plan on using SDL here for the gamepad handling unless it doesn't work with any known controllers out there.

**Comment by guusw** [comment]
Implemented and created a separate issue for the mapping screen

**Comment by nieknooijens** [comment]
nice, and SDL2 is really easy to use for that. :+1:
